### ISSUE TITLE
E_Parse Error

### ISSUE THREAD

**Issue by Hardies1** [Pierre-Lannoy/wp-apcu-manager#11]
**Describe the bug**
I received an email from Wordpress saying that an error was detected on our website. Here is the info that was included in the message:

Error Details
=============
An error of type E_PARSE was caused in line 76 of the file /home4/hopechu3/public_html/wp-content/plugins/apcu-manager/includes/libraries/decalog-sdk/EventsLogger.php. Error message: syntax error, unexpected '|', expecting variable (T_VARIABLE)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - PHP version: 8.2.18
 - WordPress version: 6.5.5
 - Other info: Divi Child theme

**Additional context**

**Comment by Pierre-Lannoy** [comment]
Hello @Hardies1 !
This error can only appear when your PHP version is lower than 8.0.
Could you confirm your PHP version?

**Comment by Hardies1** [comment]
Hi Pierre, It is interesting, In the message that I received from WordPress, it says PHP Version 7.3.33. However, when I logged into our website and checked the PHP Version using the Site Heath section of the Dashboard, it says 8.2.18. I’m not sure why there is a discrepancy between the 2 of them?   From: Pierre Lannoy ***@***.***>Date: Wednesday, June 26, 2024 at 4:22 PMTo: Pierre-Lannoy/wp-apcu-manager ***@***.***>Cc: Hardies1 ***@***.***>, Mention ***@***.***>Subject: Re: [Pierre-Lannoy/wp-apcu-manager] E_Parse Error (Issue #11)Hello @Hardies1 !This error can only appear when your PHP version is lower than 8.0.Could you confirm your PHP version?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Pierre-Lannoy** [comment]
If you execute a wp-cli command, or exec a php script execution, it may do such thing if your php is not >= 8.0.
I think you have a misconfiguration in your environment…

**Comment by Hardies1** [comment]
Our site had gone down because of an Internal Server Error. Our hosting provider fixed the problem and got our site running again. The apcu manager plugin had been deactivated during that time. I just tried reactivating it and got the following error: Plugin could not be activated because it triggered a fatal error.Fatal error: Uncaught Error: Class "DecaLog\Engine" not found in /home4/hopechu3/public_html/wp-content/plugins/apcu-manager1/apcu-manager.php:132 Stack trace: #0 /home4/hopechu3/public_html/wp-content/plugins/apcu-manager1/apcu-manager.php(155): apcm_run() #1 /home4/hopechu3/public_html/wp-admin/includes/plugin.php(2389): include_once('/home4/hopechu3...') #2 /home4/hopechu3/public_html/wp-admin/plugins.php(194): plugin_sandbox_scrape('apcu-manager1/a...') #3 {main} thrown in /home4/hopechu3/public_html/wp-content/plugins/apcu-manager1/apcu-manager.php on line 132   From: Pierre Lannoy ***@***.***>Date: Wednesday, June 26, 2024 at 4:47 PMTo: Pierre-Lannoy/wp-apcu-manager ***@***.***>Cc: Hardies1 ***@***.***>, Mention ***@***.***>Subject: Re: [Pierre-Lannoy/wp-apcu-manager] E_Parse Error (Issue #11)If you execute a wp-cli command, or exec a php script execution, it may do such thing if your php is not >= 8.0.I think you have a misconfiguration in your environment…—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
