### ISSUE TITLE
activating/deactivating plugin using wpcli throws warnings

### ISSUE THREAD

**Issue by tricarte** [Pierre-Lannoy/wp-apcu-manager#2]
Not actually a bug!

When the plugin is activated/deactivated using wpcli, it throws warnings saying that "Warning: apcu_cache_info(): No APC info available".
Of course this is due to apcu info being not available to PHP cli sapi. Commands still work as expected, they just throw warnings. Some functions in class-apcu.php suppress warnings with "@" and check the returned array is actually an array such as name() but some do not such as reset() and get_all_objects().

 - PHP version: 7.4
 - WordPress: 5.9.3

**Comment by Pierre-Lannoy** [comment]
Hello @tricarte !
Thanks for the hint. Of course, you're right: if APCu is not enabled in cli conf (and it's quite common), there are some warnings.
As you mentioned it has no influence on the operation of the plugin, but it's really uggly. I will try to fix it for the next release.
Thanks again :)
