### ISSUE TITLE
activating/deactivating the plugin using wpcli in PHP8.1 gives fatal error

### ISSUE THREAD

**Issue by tricarte** [Pierre-Lannoy/wp-apcu-manager#4]
This is actually the same as the previous issue I reported and indeed that issue is resolved. But now PHP8.1 gives fatal error:
```
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /home/xyz/sites/
sitename/public/content/plugins/apcu-manager/includes/system/class-apcu.php:119
```
This is the working command in PHP7.4:
```
/usr/bin/php7.4 $(command -v wp) plugin deactivate apcu-manager
```

And this is the command that gives the fatal error:
```
/usr/bin/php8.1 $(command -v wp) plugin deactivate apcu-manager
```

 - PHP version: 8.1
 - WordPress version: 6.0.3

**Comment by Pierre-Lannoy** [comment]
Hello @tricarte !
Thank you for this report and, OMG, you're definitely right. It is linked to #2 
It will be fixed in the next release.

Thanks again for this report…
