### ISSUE TITLE
WPML translations not shown 

### ISSUE THREAD

**Issue by cbratschi** [Pierre-Lannoy/wp-apcu-manager#6]
**Describe the bug**
I don't know if this issue is related to the APCu Manager plugin or a bug of WPML.

After translating a page, the latest changes are not shown on the page itself. Instead the previously translated value is displayed. This happens while translating the content of a WYSIWYG ACF field.

**To Reproduce**
1. Initial value is "A" for both languages.
2. Translate it to "B" still shows "A".
3. Translate it to "C" displays now "B".
4. After flushing the ACPu Manager cache, now "C" is being rendered.

**Expected behavior**
Should always use the latest translated value.

**Screenshots**
-

**Environment (please complete the following information):**
 - PHP version: 8.0
 - WordPress version and flavour: 6.1.1 (latest)
 - Other info: WPML 4.6.2 (latest), ACFML 2.0.3 (latest)

**Additional context**
-

**Comment by Asgaros** [comment]
We are having the same issues on some projects. I wonder if there is a way to somehow ensure compatibility.
